-- Schema for H2 (executed when spring.datasource.platform or spring.sql.init.platform is set to 'h2')
-- Creates USERS table expected by the application

CREATE TABLE IF NOT EXISTS USERS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP,
  created_by VARCHAR(100),
  department_id BIGINT,
  email VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  is_active BOOLEAN,
  last_name VARCHAR(100),
  password VARCHAR(255),
  phone_number VARCHAR(50),
  position VARCHAR(100),
  role VARCHAR(100),
  updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_idx ON USERS(email);

-- Password Reset Tokens table
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  expiry_date TIMESTAMP NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS password_reset_tokens_email_idx ON PASSWORD_RESET_TOKENS(email);
CREATE INDEX IF NOT EXISTS password_reset_tokens_token_idx ON PASSWORD_RESET_TOKENS(token);

-- Insert default admin user
INSERT INTO USERS (email, first_name, last_name, password, is_active, role, department_id) VALUES
('admin@interacthub.com','Admin','User','admin123', TRUE, 'ADMIN', 1);
